[2024-06-02T17:43:16.432+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T17:43:16.444+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_redshift.fetch_data_task manual__2024-06-02T17:43:11.871339+00:00 [queued]>
[2024-06-02T17:43:16.449+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_redshift.fetch_data_task manual__2024-06-02T17:43:11.871339+00:00 [queued]>
[2024-06-02T17:43:16.450+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-02T17:43:16.457+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): fetch_data_task> on 2024-06-02 17:43:11.871339+00:00
[2024-06-02T17:43:16.464+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=52) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-02T17:43:16.468+0000] {standard_task_runner.py:63} INFO - Started process 54 to run task
[2024-06-02T17:43:16.468+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_redshift', 'fetch_data_task', 'manual__2024-06-02T17:43:11.871339+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpqv9alrez']
[2024-06-02T17:43:16.470+0000] {standard_task_runner.py:91} INFO - Job 334: Subtask fetch_data_task
[2024-06-02T17:43:16.512+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_redshift.fetch_data_task manual__2024-06-02T17:43:11.871339+00:00 [running]> on host 260673f9ada7
[2024-06-02T17:43:16.575+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data Team' AIRFLOW_CTX_DAG_ID='api_to_redshift' AIRFLOW_CTX_TASK_ID='fetch_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T17:43:11.871339+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-02T17:43:11.871339+00:00'
[2024-06-02T17:43:16.577+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T17:43:16.578+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-02T17:43:16.578+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "curl 'http://api-to-s3-lambda:8080/2015-03-31/functions/function/invocations' -d '{}'"]
[2024-06-02T17:43:16.591+0000] {subprocess.py:86} INFO - Output:
[2024-06-02T17:43:16.601+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-06-02T17:43:16.602+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-06-02T17:43:16.760+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   202  100   200  100     2   1263     12 --:--:-- --:--:-- --:--:--  1278
[2024-06-02T17:43:16.761+0000] {subprocess.py:93} INFO - {"errorMessage": "Unable to import module 'lambda_function': No module named 'logger'", "errorType": "Runtime.ImportModuleError", "requestId": "7581f4f0-3b31-43fb-a07c-efd2ac57fbbe", "stackTrace": []}
[2024-06-02T17:43:16.762+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-02T17:43:16.763+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T17:43:16.826+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_to_redshift, task_id=fetch_data_task, run_id=manual__2024-06-02T17:43:11.871339+00:00, execution_date=20240602T174311, start_date=20240602T174316, end_date=20240602T174316
[2024-06-02T17:43:16.847+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T17:43:16.864+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-02T17:43:16.865+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
