[2024-06-02T17:03:20.957+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T17:03:20.970+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_redshift.load_data_task manual__2024-06-02T17:03:11.788345+00:00 [queued]>
[2024-06-02T17:03:20.975+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_redshift.load_data_task manual__2024-06-02T17:03:11.788345+00:00 [queued]>
[2024-06-02T17:03:20.975+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-02T17:03:20.981+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_data_task> on 2024-06-02 17:03:11.788345+00:00
[2024-06-02T17:03:20.986+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-02T17:03:20.988+0000] {standard_task_runner.py:63} INFO - Started process 92 to run task
[2024-06-02T17:03:20.989+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_redshift', 'load_data_task', 'manual__2024-06-02T17:03:11.788345+00:00', '--job-id', '323', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmppd5imwzx']
[2024-06-02T17:03:20.990+0000] {standard_task_runner.py:91} INFO - Job 323: Subtask load_data_task
[2024-06-02T17:03:21.027+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_redshift.load_data_task manual__2024-06-02T17:03:11.788345+00:00 [running]> on host aa1e31c12116
[2024-06-02T17:03:21.093+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data Team' AIRFLOW_CTX_DAG_ID='api_to_redshift' AIRFLOW_CTX_TASK_ID='load_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T17:03:11.788345+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-02T17:03:11.788345+00:00'
[2024-06-02T17:03:21.095+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T17:03:21.096+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-02T17:03:21.097+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "curl 'http://s3-to-redshift-lambda:8080/2015-03-31/functions/function/invocations' -d '{}'"]
[2024-06-02T17:03:21.107+0000] {subprocess.py:86} INFO - Output:
[2024-06-02T17:03:21.115+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-06-02T17:03:21.116+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-06-02T17:03:21.464+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100     2    0     0  100     2      0      9 --:--:-- --:--:-- --:--:--     9100   780  100   778  100     2   2232      5 --:--:-- --:--:-- --:--:--  2234
[2024-06-02T17:03:21.465+0000] {subprocess.py:93} INFO - {"errorMessage": "An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.", "errorType": "NoSuchKey", "requestId": "9dc8154f-ce69-47bf-ba11-e0ffbbee9aae", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 47, in lambda_handler\n    df = get_source_data()\n", "  File \"/var/task/lambda_function.py\", line 22, in get_source_data\n    response = s3_client.get_object(Bucket=source_bucket, Key=file_key)\n", "  File \"/var/lang/lib/python3.12/site-packages/botocore/client.py\", line 553, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/lang/lib/python3.12/site-packages/botocore/client.py\", line 1009, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}
[2024-06-02T17:03:21.466+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-02T17:03:21.468+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T17:03:21.491+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_to_redshift, task_id=load_data_task, run_id=manual__2024-06-02T17:03:11.788345+00:00, execution_date=20240602T170311, start_date=20240602T170320, end_date=20240602T170321
[2024-06-02T17:03:21.525+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T17:03:21.539+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T17:03:21.541+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
